version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - "ashish-thakur111"
    allowed_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true
